<?php
/**
 * Created by PhpStorm.
 * User: lengbin
 * Date: 2017/12/20
 * Time: 下午7:25
 */

namespace common\core\widget\hplus\nav;

use yii\base\Widget;

class NavWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('nav');
    }

}