<?php
/**
 * Created by PhpStorm.
 * User: lengbin
 * Date: 2017/12/29
 * Time: 上午11:23
 */

namespace common\core\filter;


use yii\base\Component;

class Menu extends Component
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}